# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MODE: CI
  WEB3: http://localhost:8545
  HEROKU_STABLE_APP_API: ute-issuer-api-stable
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  MNEMONIC: chalk park staff buzz chair purchase wise oak receive avoid avoid home

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        node-version: [14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

#      - run: PGPASSWORD=postgres psql -c 'create database origin;' -U postgres -h localhost -p 5432

      - run: yarn install

      - run: yarn build

#      - name: Deployment to Heroku
#        if: ${{ github.ref == 'refs/heads/master' }}
#        run: yarn deploy:heroku
